include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/generated_plugin_registrant.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    combinators_ordering: true
    directives_ordering: true
    omit_local_variable_types: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true